version: '3.8'
services:
  postgres:
    image: 'postgres:13.3'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user1'
      POSTGRES_PASSWORD: 'pw123456'
      POSTGRES_DB: 'testdb'
    # volumes:
    #   - dbData:/var/lib/postgresql/data
    networks:
      - privateBridge
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '2'
  # 需要單獨模擬對方回應
  # mockOrders:
  #   image: 'stoplight/prism:4'
  #   restart: always
  #   command: mock -h 0.0.0.0 "/tmp/openapi-goods.yml"
  #   volumes:
  #     - ../specs:/tmp
  #   ports:
  #     - '4010:4010'
  #   networks:
  #     - privateBridge
  #   logging:
  #     driver: json-file
  #     options:
  #       max-size: 20m
  #       max-file: '2'


# volumes:
#   dbData:

networks:
  privateBridge:
    driver: bridge