spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

server:
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: info
    com.github.ct: debug