INSERT
    INTO
        cart(
            cart_number,
            customer_name,
            total_amount,
            current_version,
            created_by,
            created_date,
            last_modified_by,
            last_modified_date
        )
    VALUES(
        '001',
        'sam',
        500,
        1,
        'sam',
        CURRENT_TIMESTAMP,
        'sam',
        CURRENT_TIMESTAMP
    );

INSERT
    INTO
        cart_product(
            id,
            cart_number,
            product_id,
            product_name,
            subtotal_amount,
            current_version,
            created_by,
            created_date,
            last_modified_by,
            last_modified_date
        )
    VALUES(
        '1',
        '001',
        '200021',
        '權威指南',
        500,
        1,
        'sam',
        CURRENT_TIMESTAMP,
        'sam',
        CURRENT_TIMESTAMP
    );
