/*
 * This file is generated by jOOQ.
 */
package com.github.ct.cart.domain.projecttions;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import org.springframework.data.domain.AbstractAggregateRoot;

/** 購物車資料 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Entity
@Table(
    name = "cart",
    uniqueConstraints = {
      @UniqueConstraint(
          name = "KEY_cart_PRIMARY",
          columnNames = {"cart_number"})
    })
@JsonIgnoreProperties(
    ignoreUnknown = true,
    value = {"hibernateLazyInitializer", "handler", "fieldHandler"})
public class Cart extends AbstractAggregateRoot implements Serializable {

  private static final long serialVersionUID = 1L;

  private String cartNumber;
  private String customerName;
  private Integer totalAmount;
  private String createdBy;
  private LocalDateTime createdDate;
  private String lastModifiedBy;
  private LocalDateTime lastModifiedDate;

  public Cart() {}

  public Cart(Cart value) {
    this.cartNumber = value.cartNumber;
    this.customerName = value.customerName;
    this.totalAmount = value.totalAmount;
    this.createdBy = value.createdBy;
    this.createdDate = value.createdDate;
    this.lastModifiedBy = value.lastModifiedBy;
    this.lastModifiedDate = value.lastModifiedDate;
  }

  public Cart(
      String cartNumber,
      String customerName,
      Integer totalAmount,
      String createdBy,
      LocalDateTime createdDate,
      String lastModifiedBy,
      LocalDateTime lastModifiedDate) {
    this.cartNumber = cartNumber;
    this.customerName = customerName;
    this.totalAmount = totalAmount;
    this.createdBy = createdBy;
    this.createdDate = createdDate;
    this.lastModifiedBy = lastModifiedBy;
    this.lastModifiedDate = lastModifiedDate;
  }

  /** Getter for <code>testdb.cart.cart_number</code>. 購物車編號 */
  @Id
  @Column(name = "cart_number", nullable = false, length = 60)
  @NotNull
  @Size(max = 60)
  public String getCartNumber() {
    return this.cartNumber;
  }

  /** Setter for <code>testdb.cart.cart_number</code>. 購物車編號 */
  public void setCartNumber(String cartNumber) {
    this.cartNumber = cartNumber;
  }

  /** Getter for <code>testdb.cart.customer_name</code>. 客戶名稱 */
  @Column(name = "customer_name", nullable = false, length = 60)
  @NotNull
  @Size(max = 60)
  public String getCustomerName() {
    return this.customerName;
  }

  /** Setter for <code>testdb.cart.customer_name</code>. 客戶名稱 */
  public void setCustomerName(String customerName) {
    this.customerName = customerName;
  }

  /** Getter for <code>testdb.cart.total_amount</code>. 金額 */
  @Column(name = "total_amount", nullable = false, precision = 10)
  @NotNull
  public Integer getTotalAmount() {
    return this.totalAmount;
  }

  /** Setter for <code>testdb.cart.total_amount</code>. 金額 */
  public void setTotalAmount(Integer totalAmount) {
    this.totalAmount = totalAmount;
  }

  /** Getter for <code>testdb.cart.created_by</code>. */
  @Column(name = "created_by", nullable = false, length = 60)
  @NotNull
  @Size(max = 60)
  public String getCreatedBy() {
    return this.createdBy;
  }

  /** Setter for <code>testdb.cart.created_by</code>. */
  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  /** Getter for <code>testdb.cart.created_date</code>. */
  @Column(name = "created_date", nullable = false)
  @NotNull
  public LocalDateTime getCreatedDate() {
    return this.createdDate;
  }

  /** Setter for <code>testdb.cart.created_date</code>. */
  public void setCreatedDate(LocalDateTime createdDate) {
    this.createdDate = createdDate;
  }

  /** Getter for <code>testdb.cart.last_modified_by</code>. */
  @Column(name = "last_modified_by", nullable = false, length = 60)
  @NotNull
  @Size(max = 60)
  public String getLastModifiedBy() {
    return this.lastModifiedBy;
  }

  /** Setter for <code>testdb.cart.last_modified_by</code>. */
  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  /** Getter for <code>testdb.cart.last_modified_date</code>. */
  @Column(name = "last_modified_date", nullable = false)
  @NotNull
  public LocalDateTime getLastModifiedDate() {
    return this.lastModifiedDate;
  }

  /** Setter for <code>testdb.cart.last_modified_date</code>. */
  public void setLastModifiedDate(LocalDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }
}
